

const SUPABASE_URL = "https://bmccxlzglxnshxwkflvx.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtY2N4bHpnbHhuc2h4d2tmbHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3NTAzODgsImV4cCI6MjEwMTMyNjM4OH0.Ra7ADR5qcsii4MHHqb5L4etbw1s0xOnyxaLojH8c_Eo";

// Supabase client banaya ja raha hai (isay change karne ki zaroorat nahi)
const supabaseClient = window.supabase.createClient("https://bmccxlzglxnshxwkflvx.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtY2N4bHpnbHhuc2h4d2tmbHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3NTAzODgsImV4cCI6MjEwMTMyNjM4OH0.Ra7ADR5qcsii4MHHqb5L4etbw1s0xOnyxaLojH8c_Eo" );
